### ISSUE TITLE
May I get write access? 

### ISSUE THREAD

**Issue by smileycreations15** [hellounicorns2/Test#4]

**Comment by MasterOfTheTiger** [comment]
Why do you need write access? A pull request would be better to do. And since this is a test repo, I do not really see a reason at all for wrote access.

**Comment by hellounicorns2** [comment]
Well you can have write access since I don’t really use GitHub much anyway.

**Comment by hellounicorns2** [comment]
Yeah turn out I don’t know how to add you to it… lol

**Comment by smileycreations15** [comment]
Settings tab > collaborators sidebar

**Comment by hellounicorns2** [comment]
Got it, I added you both!

**Comment by MasterOfTheTiger** [comment]
@hellounicorns2 I still have one question. What on earth do we need to do with write access? This is an unimportant repo...
